FROM mongo:latest


#ARG MONGO_INITDB_ROOT_USERNAME
#ARG MONGO_INITDB_ROOT_PASSWORD
#ARG MONGO_INITDB_DATABASE

#ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#ENV MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

EXPOSE 27017
